"""Optical backbone for D2NN inverse-design — accepts external phase masks.

Does NOT contain trainable phase parameters. Phase masks are injected from
outside (generated by MaskGenerator). Reuses optics.py propagation primitives.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from optics import AngularSpectrumPropagator


class PhaseMaskInjector(nn.Module):
    """Injects an external phase mask into a local sub-region of the canvas.

    Pure functional component — no nn.Parameter.
    """

    def __init__(self, canvas_size: int, phase_mask_size: int):
        super().__init__()
        self.canvas_size = int(canvas_size)
        self.phase_mask_size = int(phase_mask_size)
        if self.phase_mask_size > self.canvas_size:
            raise ValueError("phase_mask_size must be <= canvas_size.")
        self.y0 = (self.canvas_size - self.phase_mask_size) // 2
        self.x0 = (self.canvas_size - self.phase_mask_size) // 2
        self.y1 = self.y0 + self.phase_mask_size
        self.x1 = self.x0 + self.phase_mask_size

    def phase_mask_region(self):
        return [self.y0, self.y1, self.x0, self.x1]

    def forward(self, field: torch.Tensor, phase: torch.Tensor) -> torch.Tensor:
        """field: [B, H, W] complex, phase: [H, W] or [B, H, W] real in [0, 2π]."""
        field = field.to(torch.complex64)
        modulation = torch.exp(1j * phase.to(dtype=torch.float32, device=field.device))
        modulation = modulation.to(torch.complex64)
        crop = field[:, self.y0:self.y1, self.x0:self.x1]
        if modulation.ndim == 2:
            modulation = modulation.unsqueeze(0)  # [1, H, W] for broadcasting
        modulated_crop = crop * modulation
        delta = modulated_crop - crop
        return field + F.pad(
            delta,
            (self.x0, self.canvas_size - self.x1, self.y0, self.canvas_size - self.y1),
        )


class D2NNOpticalBackbone(nn.Module):
    """Fixed-geometry D2NN optical path. All optical propagation, no readout."""

    def __init__(self, config: dict):
        super().__init__()
        optics_cfg = config.get("optics", {})
        self.canvas_size = int(optics_cfg.get("canvas_size", 400))
        self.input_size = int(optics_cfg.get("input_size", 256))
        self.phase_mask_size = int(optics_cfg.get("phase_mask_size", self.input_size))
        self.phase_mask_mode = optics_cfg.get("phase_mask_mode", "centered_local")
        self.num_layers = int(optics_cfg.get("num_layers", 5))
        self.output_size = int(optics_cfg.get("output_size", 256))

        # Build propagation modules (no trainable phase params)
        self.input_to_layer_prop = AngularSpectrumPropagator(
            wavelength_m=float(optics_cfg.get("wavelength_m", 5.32e-7)),
            pixel_size_m=float(optics_cfg.get("pixel_size_m", 8.0e-6)),
            grid_size=self.canvas_size,
            distance_m=float(optics_cfg.get("input_to_layer_distance_m", 0.05)),
            evanescent_mode=optics_cfg.get("evanescent_mode", "zero"),
        )
        self.inter_prop = AngularSpectrumPropagator(
            wavelength_m=float(optics_cfg.get("wavelength_m", 5.32e-7)),
            pixel_size_m=float(optics_cfg.get("pixel_size_m", 8.0e-6)),
            grid_size=self.canvas_size,
            distance_m=float(optics_cfg.get("inter_layer_distance_m", 0.05)),
            evanescent_mode=optics_cfg.get("evanescent_mode", "zero"),
        )
        self.detector_prop = AngularSpectrumPropagator(
            wavelength_m=float(optics_cfg.get("wavelength_m", 5.32e-7)),
            pixel_size_m=float(optics_cfg.get("pixel_size_m", 8.0e-6)),
            grid_size=self.canvas_size,
            distance_m=float(optics_cfg.get("detector_distance_m", 0.05)),
            evanescent_mode=optics_cfg.get("evanescent_mode", "zero"),
        )

        # Mask injectors (functional, no learned params)
        self.injectors = nn.ModuleList([
            PhaseMaskInjector(self.canvas_size, self.phase_mask_size)
            for _ in range(self.num_layers)
        ])

    def prepare_canvas_input(self, images: torch.Tensor) -> torch.Tensor:
        """Pad 256×256 grayscale image into centre of 400×400 complex canvas."""
        if images.ndim == 3:
            images = images.unsqueeze(1)  # [B,H,W] -> [B,1,H,W]
        images = images.float()
        if tuple(images.shape[-2:]) != (self.input_size, self.input_size):
            images = F.interpolate(
                images, size=(self.input_size, self.input_size),
                mode="bilinear", align_corners=False,
            )
        canvas = torch.zeros(
            images.shape[0], self.canvas_size, self.canvas_size,
            device=images.device, dtype=torch.float32,
        )
        y0 = (self.canvas_size - self.input_size) // 2
        x0 = (self.canvas_size - self.input_size) // 2
        canvas[:, y0:y0 + self.input_size, x0:x0 + self.input_size] = images[:, 0]
        return canvas.to(torch.complex64)

    def forward(self, images: torch.Tensor, phase_masks: torch.Tensor, return_complex: bool = False) -> torch.Tensor:
        """Propagate image through optical system with externally supplied phases.

        Args:
            images: [B, H, W] or [B, 1, H, W] float tensor.
            phase_masks: [B, num_layers, mask_H, mask_W] or [num_layers, mask_H, mask_W]
                         real ∈ [0, 2π].
            return_complex: if True, return complex field at detector plane (before intensity).

        Returns:
            intensity: [B, output_size, output_size] float tensor, or
            complex field [B, canvas_size, canvas_size] if return_complex=True.
        """
        if phase_masks.ndim == 3:
            # [num_layers, H, W] → shared across batch
            phase_masks = phase_masks.unsqueeze(0).expand(images.shape[0], -1, -1, -1)
        if phase_masks.shape[1] != self.num_layers:
            raise ValueError(
                f"Expected {self.num_layers} phase masks, got {phase_masks.shape[1]}"
            )
        field = self.prepare_canvas_input(images)
        field = self.input_to_layer_prop(field)
        for i in range(self.num_layers):
            field = self.injectors[i](field, phase_masks[:, i])  # [B, H, W]
            if i < self.num_layers - 1:
                field = self.inter_prop(field)
        field = self.detector_prop(field)
        if return_complex:
            return field  # [B, canvas_size, canvas_size] complex
        intensity = torch.abs(field).square()
        # Centre-crop to output_size
        y0 = (self.canvas_size - self.output_size) // 2
        x0 = (self.canvas_size - self.output_size) // 2
        return intensity[:, y0:y0 + self.output_size, x0:x0 + self.output_size]


# Re-export from optics for convenience
__all__ = ["D2NNOpticalBackbone", "PhaseMaskInjector"]
